/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript from
 * swagger-v3.json. DO NOT MODIFY IT BY HAND — this is a genuine, unedited
 * generation output (unlike the historical swagger.ts, which drifted from
 * its own "don't hand-edit" claim). Instead, modify swagger-v3.json and run
 * `npm run generate:swagger-v3-base` to regenerate this file. Note that
 * doing so will also overwrite this banner comment with the tool's default
 * one — that's expected, the durable documentation lives in
 * swagger-v3-generation-notes.md, not here.
 *
 * These are the raw OpenAPI 3.0 types with no Atlassian-specific extensions
 * and none of the naming/typing refinements the public API has carried
 * historically. src/swagger.ts is the layer that composes this file into
 * the actual public `Swagger` namespace — see swagger-v3-generation-notes.md
 * for the full, itemized list of how and why they differ.
 */

/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Parameter".
 */
export type Parameter = ParameterWithSchema | ParameterWithContent;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchema".
 */
export type ParameterWithSchema = ParameterWithSchemaWithExample | ParameterWithSchemaWithExamples;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExample".
 */
export type ParameterWithSchemaWithExample =
  | ParameterWithSchemaWithExampleInPath
  | ParameterWithSchemaWithExampleInQuery
  | ParameterWithSchemaWithExampleInHeader
  | ParameterWithSchemaWithExampleInCookie;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExamples".
 */
export type ParameterWithSchemaWithExamples =
  | ParameterWithSchemaWithExamplesInPath
  | ParameterWithSchemaWithExamplesInQuery
  | ParameterWithSchemaWithExamplesInHeader
  | ParameterWithSchemaWithExamplesInCookie;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithContent".
 */
export type ParameterWithContent = ParameterWithContentInPath | ParameterWithContentNotInPath;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "MediaType".
 */
export type MediaType = MediaTypeWithExample | MediaTypeWithExamples;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Header".
 */
export type Header = HeaderWithSchema | HeaderWithContent;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "HeaderWithSchema".
 */
export type HeaderWithSchema = HeaderWithSchemaWithExample | HeaderWithSchemaWithExamples;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Link".
 */
export type Link = LinkWithOperationRef | LinkWithOperationId;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "SecurityScheme".
 */
export type SecurityScheme =
  APIKeySecurityScheme | HTTPSecurityScheme | OAuth2SecurityScheme | OpenIdConnectSecurityScheme;
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "HTTPSecurityScheme".
 */
export type HTTPSecurityScheme = NonBearerHTTPSecurityScheme | BearerHTTPSecurityScheme;

export interface SwaggerV3 {
  openapi: string;
  info: Info;
  externalDocs?: ExternalDocumentation;
  servers?: Server[];
  security?: SecurityRequirement[];
  tags?: Tag[];
  paths: Paths;
  components?: Components;
  /**
   * This interface was referenced by `SwaggerV3`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Info".
 */
export interface Info {
  title: string;
  description?: string;
  termsOfService?: string;
  contact?: Contact;
  license?: License;
  version: string;
  /**
   * This interface was referenced by `Info`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Contact".
 */
export interface Contact {
  name?: string;
  url?: string;
  email?: string;
  /**
   * This interface was referenced by `Contact`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "License".
 */
export interface License {
  name: string;
  url?: string;
  /**
   * This interface was referenced by `License`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ExternalDocumentation".
 */
export interface ExternalDocumentation {
  description?: string;
  url: string;
  /**
   * This interface was referenced by `ExternalDocumentation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Server".
 */
export interface Server {
  url: string;
  description?: string;
  variables?: {
    [k: string]: ServerVariable;
  };
  /**
   * This interface was referenced by `Server`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ServerVariable".
 */
export interface ServerVariable {
  enum?: string[];
  default: string;
  description?: string;
  /**
   * This interface was referenced by `ServerVariable`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "SecurityRequirement".
 */
export interface SecurityRequirement {
  [k: string]: string[];
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Tag".
 */
export interface Tag {
  name: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  /**
   * This interface was referenced by `Tag`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Paths".
 */
export interface Paths {}
/**
 * This interface was referenced by `Paths`'s JSON-Schema definition
 * via the `patternProperty` "^\/".
 *
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "PathItem".
 */
export interface PathItem {
  $ref?: string;
  summary?: string;
  description?: string;
  get?: Operation;
  put?: Operation;
  post?: Operation;
  delete?: Operation;
  options?: Operation;
  head?: Operation;
  patch?: Operation;
  trace?: Operation;
  servers?: Server[];
  parameters?: (Parameter | Reference)[];
  /**
   * This interface was referenced by `PathItem`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Operation".
 */
export interface Operation {
  tags?: string[];
  summary?: string;
  description?: string;
  externalDocs?: ExternalDocumentation;
  operationId?: string;
  parameters?: (Parameter | Reference)[];
  requestBody?: RequestBody | Reference;
  responses: Responses;
  callbacks?: {
    [k: string]: Callback | Reference;
  };
  deprecated?: boolean;
  security?: SecurityRequirement[];
  servers?: Server[];
  /**
   * This interface was referenced by `Operation`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExampleInPath".
 */
export interface ParameterWithSchemaWithExampleInPath {
  name: string;
  in: 'path';
  description?: string;
  required: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'matrix' | 'label' | 'simple';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Schema".
 */
export interface Schema {
  title?: string;
  multipleOf?: number;
  maximum?: number;
  exclusiveMaximum?: boolean;
  minimum?: number;
  exclusiveMinimum?: boolean;
  maxLength?: number;
  minLength?: number;
  pattern?: string;
  maxItems?: number;
  minItems?: number;
  uniqueItems?: boolean;
  maxProperties?: number;
  minProperties?: number;
  /**
   * @minItems 1
   */
  required?: [string, ...string[]];
  /**
   * @minItems 1
   */
  enum?: [any, ...any[]];
  type?: 'array' | 'boolean' | 'integer' | 'number' | 'object' | 'string';
  not?: Schema | Reference;
  allOf?: (Schema | Reference)[];
  oneOf?: (Schema | Reference)[];
  anyOf?: (Schema | Reference)[];
  items?: Schema | Reference;
  properties?: {
    [k: string]: Schema | Reference;
  };
  additionalProperties?: Schema | Reference | boolean;
  description?: string;
  format?: string;
  default?: any;
  nullable?: boolean;
  discriminator?: Discriminator;
  readOnly?: boolean;
  writeOnly?: boolean;
  example?: any;
  externalDocs?: ExternalDocumentation;
  deprecated?: boolean;
  xml?: XML;
  /**
   * This interface was referenced by `Schema`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Reference".
 */
export interface Reference {
  $ref: string;
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Discriminator".
 */
export interface Discriminator {
  propertyName: string;
  mapping?: {
    [k: string]: string;
  };
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "XML".
 */
export interface XML {
  name?: string;
  namespace?: string;
  prefix?: string;
  attribute?: boolean;
  wrapped?: boolean;
  /**
   * This interface was referenced by `XML`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExampleInQuery".
 */
export interface ParameterWithSchemaWithExampleInQuery {
  name: string;
  in: 'query';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'form' | 'spaceDelimited' | 'pipeDelimited' | 'deepObject';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInQuery`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExampleInHeader".
 */
export interface ParameterWithSchemaWithExampleInHeader {
  name: string;
  in: 'header';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'simple';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInHeader`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExampleInCookie".
 */
export interface ParameterWithSchemaWithExampleInCookie {
  name: string;
  in: 'cookie';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'form';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `ParameterWithSchemaWithExampleInCookie`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExamplesInPath".
 */
export interface ParameterWithSchemaWithExamplesInPath {
  name: string;
  in: 'path';
  description?: string;
  required: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'matrix' | 'label' | 'simple';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Example".
 */
export interface Example {
  summary?: string;
  description?: string;
  value?: any;
  externalValue?: string;
  /**
   * This interface was referenced by `Example`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExamplesInQuery".
 */
export interface ParameterWithSchemaWithExamplesInQuery {
  name: string;
  in: 'query';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'form' | 'spaceDelimited' | 'pipeDelimited' | 'deepObject';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInQuery`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExamplesInHeader".
 */
export interface ParameterWithSchemaWithExamplesInHeader {
  name: string;
  in: 'header';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'simple';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInHeader`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithSchemaWithExamplesInCookie".
 */
export interface ParameterWithSchemaWithExamplesInCookie {
  name: string;
  in: 'cookie';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'form';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `ParameterWithSchemaWithExamplesInCookie`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithContentInPath".
 */
export interface ParameterWithContentInPath {
  name: string;
  in: 'path';
  description?: string;
  required?: true;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `ParameterWithContentInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "MediaTypeWithExample".
 */
export interface MediaTypeWithExample {
  schema?: Schema | Reference;
  example?: any;
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `MediaTypeWithExample`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Encoding".
 */
export interface Encoding {
  contentType?: string;
  headers?: {
    [k: string]: Header;
  };
  style?: 'form' | 'spaceDelimited' | 'pipeDelimited' | 'deepObject';
  explode?: boolean;
  allowReserved?: boolean;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "HeaderWithSchemaWithExample".
 */
export interface HeaderWithSchemaWithExample {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'simple';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  example?: any;
  /**
   * This interface was referenced by `HeaderWithSchemaWithExample`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "HeaderWithSchemaWithExamples".
 */
export interface HeaderWithSchemaWithExamples {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  style?: 'simple';
  explode?: boolean;
  allowReserved?: boolean;
  schema: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  /**
   * This interface was referenced by `HeaderWithSchemaWithExamples`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "HeaderWithContent".
 */
export interface HeaderWithContent {
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `HeaderWithContent`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "MediaTypeWithExamples".
 */
export interface MediaTypeWithExamples {
  schema?: Schema | Reference;
  examples: {
    [k: string]: Example | Reference;
  };
  encoding?: {
    [k: string]: Encoding;
  };
  /**
   * This interface was referenced by `MediaTypeWithExamples`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ParameterWithContentNotInPath".
 */
export interface ParameterWithContentNotInPath {
  name: string;
  in: 'query' | 'header' | 'cookie';
  description?: string;
  required?: boolean;
  deprecated?: boolean;
  allowEmptyValue?: boolean;
  content: {
    [k: string]: MediaType;
  };
  /**
   * This interface was referenced by `ParameterWithContentNotInPath`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "RequestBody".
 */
export interface RequestBody {
  description?: string;
  content: {
    [k: string]: MediaType;
  };
  required?: boolean;
  /**
   * This interface was referenced by `RequestBody`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Responses".
 */
export interface Responses {
  default?: Response | Reference;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Response".
 */
export interface Response {
  description: string;
  headers?: {
    [k: string]: Header | Reference;
  };
  content?: {
    [k: string]: MediaType;
  };
  links?: {
    [k: string]: Link | Reference;
  };
  /**
   * This interface was referenced by `Response`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "LinkWithOperationRef".
 */
export interface LinkWithOperationRef {
  operationRef?: string;
  parameters?: {
    [k: string]: any;
  };
  requestBody?: any;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `LinkWithOperationRef`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "LinkWithOperationId".
 */
export interface LinkWithOperationId {
  operationId?: string;
  parameters?: {
    [k: string]: any;
  };
  requestBody?: any;
  description?: string;
  server?: Server;
  /**
   * This interface was referenced by `LinkWithOperationId`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Callback".
 */
export interface Callback {
  [k: string]: PathItem;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "Components".
 */
export interface Components {
  schemas?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Schema;
  };
  responses?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Response;
  };
  parameters?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Parameter;
  };
  examples?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Example;
  };
  requestBodies?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | RequestBody;
  };
  headers?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Header;
  };
  securitySchemes?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | SecurityScheme;
  };
  links?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Link;
  };
  callbacks?: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-zA-Z0-9\.\-_]+$".
     */
    [k: string]: Reference | Callback;
  };
  /**
   * This interface was referenced by `Components`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "APIKeySecurityScheme".
 */
export interface APIKeySecurityScheme {
  type: 'apiKey';
  name: string;
  in: 'header' | 'query' | 'cookie';
  description?: string;
  /**
   * This interface was referenced by `APIKeySecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "NonBearerHTTPSecurityScheme".
 */
export interface NonBearerHTTPSecurityScheme {
  scheme: string;
  description?: string;
  type: 'http';
  /**
   * This interface was referenced by `NonBearerHTTPSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "BearerHTTPSecurityScheme".
 */
export interface BearerHTTPSecurityScheme {
  scheme: 'bearer';
  bearerFormat?: string;
  type: 'http';
  description?: string;
  /**
   * This interface was referenced by `BearerHTTPSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "OAuth2SecurityScheme".
 */
export interface OAuth2SecurityScheme {
  type: 'oauth2';
  flows: OAuthFlows;
  description?: string;
  /**
   * This interface was referenced by `OAuth2SecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "OAuthFlows".
 */
export interface OAuthFlows {
  implicit?: ImplicitOAuthFlow;
  password?: PasswordOAuthFlow;
  clientCredentials?: ClientCredentialsFlow;
  authorizationCode?: AuthorizationCodeOAuthFlow;
  /**
   * This interface was referenced by `OAuthFlows`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ImplicitOAuthFlow".
 */
export interface ImplicitOAuthFlow {
  authorizationUrl: string;
  refreshUrl?: string;
  scopes: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ImplicitOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "PasswordOAuthFlow".
 */
export interface PasswordOAuthFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `PasswordOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "ClientCredentialsFlow".
 */
export interface ClientCredentialsFlow {
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `ClientCredentialsFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "AuthorizationCodeOAuthFlow".
 */
export interface AuthorizationCodeOAuthFlow {
  authorizationUrl: string;
  tokenUrl: string;
  refreshUrl?: string;
  scopes?: {
    [k: string]: string;
  };
  /**
   * This interface was referenced by `AuthorizationCodeOAuthFlow`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
/**
 * This interface was referenced by `SwaggerV3`'s JSON-Schema
 * via the `definition` "OpenIdConnectSecurityScheme".
 */
export interface OpenIdConnectSecurityScheme {
  type: 'openIdConnect';
  openIdConnectUrl: string;
  description?: string;
  /**
   * This interface was referenced by `OpenIdConnectSecurityScheme`'s JSON-Schema definition
   * via the `patternProperty` "^x-".
   */
  [k: string]: any;
}
